/**
 * @license
 * Copyright 2022 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

import {Injectable} from '@angular/core';
import {Store} from '@ngrx/store';

import {CalculateDiffsRequest, CalculateDiffsResponse, TensorResults, WorkerCommand, WorkerMessage} from '../common/types';
import {RunTask, TaskStatus} from '../data_model/misc';
import {TensorMap} from '../data_model/run_results';
import {setDiffs, updateRunTaskStatus} from '../store/actions';
import {AppState} from '../store/state';

/**
 * Service for custom inputs (generated by code editor) related tasks.
 */
@Injectable({
  providedIn: 'root',
})
export class CustomInputsService {
  private curTensorResults?: TensorResults;

  setTensorResults(results: TensorResults|undefined) {
    this.curTensorResults = results;
  }

  getCurTensorResults() {
    return this.curTensorResults;
  }
}
